// Landmarks the seed data clusters around.
//
// `sparse` marks a place whose photos are deliberately scattered 140-240m out,
// so that capturing at its centre finds fewer than three neighbours and the
// 100m -> 250m fallback visibly fires. Every demo needs one of these.
//
// Coordinates are mirrored in ios/Nimbus/Model/Place.swift for the travel
// simulator; keep the two in sync if you add a landmark.

export const PLACES = [
  {
    id: 'eiffel',
    name: 'Eiffel Tower',
    city: 'Paris',
    lat: 48.8584,
    lon: 2.2945,
    hero: 'tower',
    photos: 6,
    captions: [
      'Waited an hour for the light to go gold. Worth it.',
      'It sparkles on the hour and everyone stops talking.',
      'Third time in Paris, first time I actually looked up.',
      'Champ de Mars, cheap wine, no regrets.',
      'My mother stood here in 1978. Same angle.',
      'Rained all day then this happened at 9pm.',
    ],
  },
  {
    id: 'golden-gate',
    name: 'Golden Gate Bridge',
    city: 'San Francisco',
    lat: 37.8199,
    lon: -122.4783,
    hero: 'bridge',
    water: true,
    photos: 5,
    captions: [
      'Fog burned off for about four minutes. Got it.',
      'Biked across and my hands went numb.',
      'You can hear it humming if you stand still.',
      'Everyone told me it would be smaller.',
      'Battery Spencer at 6am, freezing, alone.',
    ],
  },
  {
    id: 'shibuya',
    name: 'Shibuya Crossing',
    city: 'Tokyo',
    lat: 35.6595,
    lon: 139.7005,
    hero: 'neon',
    photos: 6,
    captions: [
      '3000 people and nobody touched anybody.',
      'Watched four cycles from the window upstairs.',
      'Rain makes the whole intersection a mirror.',
      'Jet lag at 2am and it was still like this.',
      'Lost my friend here for 40 minutes.',
      'The dog statue has its own queue.',
    ],
  },
  {
    id: 'times-square',
    name: 'Times Square',
    city: 'New York',
    lat: 40.758,
    lon: -73.9855,
    hero: 'neon',
    photos: 5,
    captions: [
      'Never dark. Genuinely never.',
      'Tourists hate it, I love it, we are not the same.',
      'Snowing sideways and the screens still screaming.',
      'First night in the city, could not sleep, came here.',
      'Someone was playing a saxophone perfectly.',
    ],
  },
  {
    id: 'sagrada',
    name: 'Sagrada Família',
    city: 'Barcelona',
    lat: 41.4036,
    lon: 2.1744,
    hero: 'spires',
    photos: 5,
    captions: [
      'Still unfinished after 140 years. Somehow reassuring.',
      'The light inside at 4pm is not real.',
      'Cranes in every photo and I stopped minding.',
      'Sat in the park opposite for two hours.',
      'Gaudí is buried underneath it.',
    ],
  },
  {
    id: 'colosseum',
    name: 'Colosseum',
    city: 'Rome',
    lat: 41.8902,
    lon: 12.4922,
    hero: 'arches',
    photos: 5,
    captions: [
      'Lit up at night and completely empty at 11pm.',
      'Two thousand years and it is just there, at a roundabout.',
      'Cats living in the ruins across the road.',
      'August, 39 degrees, no shade, still glad.',
      'You can see where the marble was stripped off.',
    ],
  },
  {
    id: 'opera-house',
    name: 'Sydney Opera House',
    city: 'Sydney',
    lat: -33.8568,
    lon: 151.2153,
    hero: 'shells',
    water: true,
    photos: 5,
    captions: [
      'The tiles are not white. Nobody tells you that.',
      'Ferry from Manly, best two dollars I ever spent.',
      'Ate chips on the steps and a gull took one.',
      'New Year and the harbour was full of boats.',
      'Circular Quay at dawn, completely still.',
    ],
  },
  {
    id: 'marina-bay',
    name: 'Marina Bay Sands',
    city: 'Singapore',
    lat: 1.2834,
    lon: 103.8607,
    hero: 'skyline',
    water: true,
    photos: 4,
    captions: [
      'Light show at 8pm, whole waterfront stops.',
      'Humidity like walking into a wall.',
      'From the Gardens side, just before the storm.',
      'That is a boat. On top of three towers.',
    ],
  },
  {
    id: 'table-mountain',
    name: 'Table Mountain',
    city: 'Cape Town',
    lat: -33.9628,
    lon: 18.4098,
    hero: 'mountain',
    photos: 4,
    captions: [
      'The cloud pours over the edge like a tablecloth.',
      'Cable car closed so we walked. Four hours.',
      'You can see two oceans from up here, allegedly.',
      'Wind nearly took my hat to Antarctica.',
    ],
  },
  {
    id: 'griffith',
    name: 'Griffith Observatory',
    city: 'Los Angeles',
    lat: 34.1184,
    lon: -118.3004,
    hero: 'observatory',
    sparse: true, // scattered wide on purpose: triggers the 250m fallback
    photos: 4,
    captions: [
      'Whole basin lit up and the air actually clear.',
      'Parked a mile down the hill like everyone else.',
      'Saw Saturn through the telescope, queued 50 minutes.',
      'Hiked up from Fern Dell at sunset.',
    ],
  },
  {
    id: 'brooklyn-bridge',
    name: 'Brooklyn Bridge',
    city: 'New York',
    lat: 40.7061,
    lon: -73.9969,
    hero: 'bridge',
    water: true,
    photos: 5,
    captions: [
      'Walked it at 6am to have it to myself.',
      'Cyclists will end you if you stand in the lane.',
      'The cables make a harp out of the skyline.',
      'Manhattan side, first snow of the year.',
      'Ice cream under the bridge afterwards.',
    ],
  },
  {
    id: 'trevi',
    name: 'Trevi Fountain',
    city: 'Rome',
    lat: 41.9009,
    lon: 12.4833,
    hero: 'fountain',
    photos: 5,
    captions: [
      'You turn a corner and it is just enormous.',
      'Threw a coin. Obviously.',
      'Came back at 1am and had it almost to myself.',
      'They pull about 3000 euros out of it a day.',
      'Loudest water I have ever heard in a city.',
    ],
  },
];

export const SEED_USERS = [
  { id: 'seed-mira', displayName: 'Mira Okonkwo', color: '#F2A65A' },
  { id: 'seed-julien', displayName: 'Julien Rocher', color: '#6EA8FF' },
  { id: 'seed-ana', displayName: 'Ana Beltrán', color: '#F2789A' },
  { id: 'seed-kenji', displayName: 'Kenji Tanaka', color: '#7ED9A0' },
  { id: 'seed-priya', displayName: 'Priya Raman', color: '#C79BFF' },
  { id: 'seed-tomas', displayName: 'Tomas Lindqvist', color: '#5ED2E0' },
  { id: 'seed-zoe', displayName: 'Zoë Marchetti', color: '#FFD166' },
  { id: 'seed-samir', displayName: 'Samir Haddad', color: '#FF8A5C' },
];
